### ISSUE TITLE
Queue problems when deploying

### ISSUE THREAD

**Issue by empereira** [FOGProject/fogproject#691]
Hello,

I am experiencing an issue with deployment tasks in FOG. I have groups of hosts, for example, LAB02.

I click on LAB02, go to the Basic Tasks tab, and select Deploy.

I enable (fogserver default conf):
- Wake on LAN
- Schedule Instant
- I click the button to create the deployment tasks.
- In the Task Management menu, I see that the first 6 machines start deploying.
- However, once those 6 machines complete the deployment, no new machines start, even though the group has more hosts.

Troubleshooting steps I have tried:
- I checked Max Clients in the Storage Management, and it is set to 10.
- Restarted the services:
- systemctl restart FOGImageReplicator FOGScheduler FOGSnapinReplicator
- Checked Task Management, but no new tasks are created automatically.
- Ensured that the PXE boot settings on the remaining machines are correct.

Additional notes:

I noticed that the FOG_QUEUESIZE setting seems to have been removed in the latest version. Could this be related to the issue?
Is there any way to force the queued machines to start once the first batch finishes?
Am I missing any settings to allow the next hosts to start deployment after the first batch completes?
Any guidance on this would be greatly appreciated. Thanks!
 
---------------------------------------
You are not running the most current version of FOG!
You are currently running version: 1.5.10.1629
Latest stable version is 1.5.10.1639
Latest dev-branch version is 1.5.10.1639
Latest alpha-branch version is 1.6.0-beta.2166e help you?

_____________________________

I updated to version 1.5.10.1639, but this morning we sent some more tasks, 31 in total, and after finishing the first 10, it keeps waiting endlessly.

The strange thing is that all the machines in the queue say that there are, for example, 15 before me. Is that correct?

It shouldn’t be like that:
- the first 10 start
- The message on the 11th: “Are slots open, but 10 before me”?
- The message on 12: “Are slots open, but 11 before me”?

… and so on?

**Comment by mastacontrola** [comment]
I'm not sure how I can attempt to replicate the issue. It's not that I'm/we're not concerned, rather I don't know how to replicate to see the issue.

I would imagine, if this were as widespread an issue, we'd be likely seeing it year after year as I'm not aware of the queueing system being changed anytime recently.

**Comment by empereira** [comment]
> I'm not sure how I can attempt to replicate the issue. It's not that I'm/we're not concerned, rather I don't know how to replicate to see the issue.
> 
> I would imagine, if this were as widespread an issue, we'd be likely seeing it year after year as I'm not aware of the queueing system being changed anytime recently.

hello @mastacontrola ,

I also don't know how to help in a scenario where you can replicate this problem.

As computer classes are in progress at the moment, I can't send a new task.

Is there anything I could debug to help with this problem?

**Comment by lukebarone** [comment]
Are they all on the same physical network switch? Are the settings in the
BIOSes the same across the board (especially in regards to the Wake on LAN
features)?

**Comment by empereira** [comment]
> Are they all on the same physical network switch? Are the settings in the
> BIOSes the same across the board (especially in regards to the Wake on LAN
> features)?
> […](#)

Yes, they're all on the same switch.

If you mean the BIOS of each machine, yes, we configure them all via UEFI, with wake-on-lan. They're all on the same bios version.

If you mean the DHCP bios configuration, that's correct, in principle.

![Image](https://github.com/user-attachments/assets/768f2419-a03d-4c8d-938c-5c59d2a5ed36)

**Comment by DBailey635** [comment]
I’ve got exactly the same problem. The initial 10 queue items complete, but the next ones from same group won’t start when any of the first 10 slots are freed up. I have to click the lightning bolt icon in the task list to force it to start. Looking at every machine pending in the room, all of them display "no open slots" and none of them show less than "there are 15 before me", despite the 10 initial tasks having completed.

![Image](https://github.com/user-attachments/assets/88020104-6bfd-44d2-921a-8b16f9626288)

Am running up to date FOG software on a fully patched Ubuntu server. All Dell machines and the server are on same subnet. If you need any specific details to help diagnose this, just ask and I'll do my best to collect data.

**Comment by leo150250** [comment]
Hi, I have the same problem right now.

We made a storage with 4 max clients. The first 4 deployments went normal but the remaining are stuck in "no open slots" message.

The FOG server shows that there are 38 hosts queued, 0 active and 0 free (not the 4 that's specified on the storage), as if the hosts aren't messaging the server when the deployment is completed, and the server doesn't even update when a host completes, although their respective tasks are flagged as completed on the database.

The current version is 1.5.10.1639, installed as container on a Proxmox Server using their templates.

**Comment by darksidemilk** [comment]
If you change your available from 4 to 5 does 1 start?
If you're on redhat based linux like Rocky or Alma then check the /var/log/php-fpm/www-error.log I don't recall the Debian equivalent off the top of my head. Sounds like the queue isn't being reset. I don't know when I'll have time to look at this in detail, but the more debug info we have the faster we can trace it.

**Comment by leo150250** [comment]
Yes, if I add another slot, one host starts deploying.

I've noticed that this happens more commonly if I had a lot of hosts on queue. For example, this happened when I queued 38 hosts but, if I had 4 slots and 5 on queue, the 5th host queued deploys normally once a slot opens.

I wonder if I set 4 slots and queue 8 hosts, the queued ones would deploy normally after the first 4, but maybe with 9 hosts on queue the problem should appears? Maybe there's something with the check-ins of the hosts?

**Comment by darksidemilk** [comment]
It just came to my memory that I did make some changes to the queuing system, or at least something related to it, not that long ago. It fixed an issue where hosts weren't starting as scheduled in a race case situation. I sadly don't have the time to debug this right now. But something to try would be manually reverting the changes in this commit https://github.com/FOGProject/fogproject/commit/eea8267ae73fcc6c383a20f45d4f0a8601f9f180 
just to determine if the changes to fix that issue caused this.
You might do this by finding the matching files in that commit at their /var/www/fog/lib paths and replacing what changed with what it used to be. You can undo this change by re-running the installer to get back to the latest version, or you can have made .bak/.old versions of the files before making changes to them.

**Comment by cbrherms** [comment]
Just to throw in my 2p, also seeing this on my own instance of version 1.5.10.1655
If only a couple of hosts queued up at same time, they run fine. More than that and they all get stuck in the queue with apparently no open slots until i manually start them. Will try reverting that change.

**Comment by cbrherms** [comment]
That does appear to have been the cause. Reverted those changes and now large batches start as expected with all machines checking in and moving up the queue.

**Comment by darksidemilk** [comment]
@cbrherms thank you for giving that a go.
I'm seeing if I can find the issue so this issue gets resolved without losing what that change fixed.

**Comment by darksidemilk** [comment]
@leo150250 @empereira  @DBailey635  @cbrherms 
I just pushed a potential fix to the dev-branch and to working-1.6.
In my local testing the problem was fixed. If you friends could update using either of those branches and let me know if that did the trick it would be much appreciated. 
If we don't hear anything we'll assume it worked based on my testing and it will be automatically put into stable on the 15th of next month with the automatic release.

**Comment by cbrherms** [comment]
That appears to have worked for me.
I did initially think there was still a problem, but turns out my reimaging process was creating a quite specific race condition in certain situations that i'll open up a new issue for.

**Comment by darksidemilk** [comment]
We actually just pushed a new and better fix to the 1.6 branch for this. This first fix didn't quite get the queue working properly but proved where the issue was, the new one should have it sorted. @mastacontrola or I will hopefully have the time to port it to the dev-branch tomorrow for testing there, or you can test it in working-1.6 now, which is the "beta" version of fog and we would love more testers. Honestly, I think it's production ready, as I use it in production, but there are workflows and plug-ins I don't use that we need feedback on.

**Comment by darksidemilk** [comment]
@leo150250 @empereira @DBailey635 

This should now be more fully flushed out and fixed in both working-1.6 and dev-branch.
If you could update to the dev-branch or working-1.6 and let us know if it fixes the issue, it would be much appreciated. For a refresher on installing/updating or switching branches see https://docs.fogproject.org/en/latest/install-fog-server

See also #736 

Here's a link to the diff for 1.6 with the fix after all related commits https://github.com/FOGProject/fogproject/compare/5c3e9cd..d458a4f

Here's the same for dev-branch
https://github.com/FOGProject/fogproject/compare/5d49e85..1f113f7

**Comment by leo150250** [comment]
I've made an update to working-1.6 but could not test it already, because LDAP authentication broke up after update, as detailed in issue #737 .

But we figured that the fog user is still working so in meantime we'll be trying to mass queue to figure out if the queue issue has been fixed.

**Comment by leo150250** [comment]
✅ We've forced now a imaging on 2 computers using only one slot and, it worked as expected, although I want to test more by putting more computers than slots to see if the queue still works as expected, for example, 3 slots for 20 computers. We just need to identify and set a maintenance window here.

**Comment by darksidemilk** [comment]
For reference here's what queued hosts should look like while they're waiting now (minus the 'press enter to continue' that's only debug mode)

<img width="820" height="66" alt="Image" src="https://github.com/user-attachments/assets/ca4be593-72b2-4c55-8e7b-f6c7b0ef3db4" />

<img width="793" height="125" alt="Image" src="https://github.com/user-attachments/assets/6aab46eb-1522-4258-abbe-65ca10de4b59" />

<img width="762" height="78" alt="Image" src="https://github.com/user-attachments/assets/f10f40ee-850d-4a6f-9779-ff1a7f364217" />

**Comment by darksidemilk** [comment]
Updated further to base queue on taskID as it's atomic, essentially if a task needs to wait it will be based on when the task was created rather than when it checked in.
See https://github.com/FOGProject/fogproject/commit/6b9ce0ac202af4f90d406de50ad2b34650d03719

Currently just in 1.6 will try to get it ported down.

**Comment by darksidemilk** [comment]
Reworked it one more time after discovering we already had another date field in the task table that was no longer used. Now we're tracking when a host first checked in and a separate check in to check if the task is actively checking in and waiting to start.
So it now will not have any random queue jumps and it will expire tasks that don't checkin within the FOG_CHECKIN_TIMEOUT which defaults to 600 seconds (10 minutes).

Tldr
The imaging task queue is fixed and is based on when each host/task checks in

**Comment by leo150250** [comment]
✅ We made another test imaging 16 computers with 1 slot only. Queue worked perfectly fine.

✅ During imaging, we changed to 4 slots and queue still worked perfectly fine imaging 4 computers simultaneously, starting another everytime one finished.

_All systems green!_

**Comment by darksidemilk** [comment]
> ✅ We made another test imaging 16 computers with 1 slot only. Queue worked perfectly fine.
> 
> ✅ During imaging, we changed to 4 slots and queue still worked perfectly fine imaging 4 computers simultaneously, starting another everytime one finished.
> 
> _All systems green!_

@leo150250  Was this in working-1.6 or dev-branch? Both should be working, just want to be sure we know which one you're confirming worked.

**Comment by leo150250** [comment]
In working-1.6 branch.

**Comment by darksidemilk** [comment]
Thank you for testing that out! I think once we hear from someone that has tested it in dev-branch we'll close this out.

**Comment by cbrherms** [comment]
Ran a 100 machine run on dev-branch (1.5.10.1692), and everything seemed to queue correctly.
Only weird thing was around 5 machines ended up with incompletely copied or possibly corrupt partitions, and booted to windows recovery citing missing system files; But, i'm not sure whether that could be related to any of the changes, or just a fluke - just not something i've seen before.

**Comment by darksidemilk** [comment]
If it was only 5 machines, that sounds like an unfortunate coincidence of issues on just those machines. All the actual disk operations are in FOS which we haven't touched as we adjusted the queue system.
Provided re-imaging that group of machines with issues works on the second try or you can confirm whether those ones have a hardware issue or something like that.

**Comment by cbrherms** [comment]
I think it was just coincidental, yes. 
Either way, all are sorted now and was fine on the second run (I did around 20, so some redeploys just to check queuing again).

All seems to be working as expected.
