### ISSUE TITLE
Help: After booting from FOG to GRUB in the VM, a "KERNEL PANIC!" error occurs.

### ISSUE THREAD

**Issue by ZephyrBD** [FOGProject/fogproject#766]
I've set up EFI Network in the VMware virtual machine. 
When I select "Boot from hard disk" from the FOG menu, after briefly going through rEFInd, it reaches the GRUB interface. 
However, when starting Ubuntu from here, an error occurs. But if I directly boot to GRUB, I can enter the system normally. 
Can anyone help me solve this problem?

<img width="350" height="144" alt="Image" src="https://github.com/user-attachments/assets/d5ee7b9d-dd2e-4a64-842e-a0447fcec1b0" />

<img width="298" height="61" alt="Image" src="https://github.com/user-attachments/assets/c08f9592-ede1-4a84-8a5c-4662af532353" />

<img width="538" height="186" alt="Image" src="https://github.com/user-attachments/assets/c48ad8af-62a0-4cfe-aada-0b54740fe333" />

**Comment by darksidemilk** [comment]
Provided you're on a more recent version of FOG, try using the SANBOOT exit option instead of rEFInd.
iPxe added support for direct disk booting for efi disks and we've implemented that in fog. I imagine that will help.

**Comment by ZephyrBD** [comment]
> Provided you're on a more recent version of FOG, try using the SANBOOT exit option instead of rEFInd. iPxe added support for direct disk booting for efi disks and we've implemented that in fog. I imagine that will help.

After setting SANBOOT exit, it still doesn't seem to work, and I can't even enter GRUB now, as specifically shown in the GIF below. By the way, is rEFInd the bootloader of VMware? Can it be replaced?

![Image](https://github.com/user-attachments/assets/cc3636ee-33d0-4c4e-8bfa-75456a8ea2b5)

**Comment by darksidemilk** [comment]
What version of FOG are you running?

rEFInd is a bootloader we used to make the boot menu work when EFI came around because the old SANBOOT method that would boot to the disk from ipxe stopped working in EFI until ipxe added support recently. If you're not on the latest version of FOG then SANBOOT may not do the trick and would look like what I see in your gif, but I also don't work much with linux images, so there could be something else at play there.

**Comment by ZephyrBD** [comment]
> What version of FOG are you running?
> 
> rEFInd is a bootloader we used to make the boot menu work when EFI came around because the old SANBOOT method that would boot to the disk from ipxe stopped working in EFI until ipxe added support recently. If you're not on the latest version of FOG then SANBOOT may not do the trick and would look like what I see in your gif, but I also don't work much with linux images, so there could be something else at play there.

I'm running version 1.5.10.1734. Also, I'm wondering if this issue only occurs in virtual machines and might disappear on physical machines (but I'm still researching, so I haven't tried it on a physical machine yet).

**Comment by darksidemilk** [comment]
Is this a simple single disk setup, or are there multiple disks and or special partitions?
You could try the grub exit option, but I'm unsure that will do the trick. You also don't have to leave a host booting to FOG every time after imaging, you can set things up to change the boot order after imaging. There are ways to make it change back on demand.

**Comment by ZephyrBD** [comment]
> > What version of FOG are you running?
> > 
> > rEFInd is a bootloader we used to make the boot menu work when EFI came around because the old SANBOOT method that would boot to the disk from ipxe stopped working in EFI until ipxe added support recently. If you're not on the latest version of FOG then SANBOOT may not do the trick and would look like what I see in your gif, but I also don't work much with linux images, so there could be something else at play there.
> 
> I'm running version 1.5.10.1734. Also, I'm wondering if this issue only occurs in virtual machines and might disappear on physical machines (but I'm still researching, so I haven't tried it on a physical machine yet).
> 
> 
I'm afraid I didn't make the previous problem clear, so let me rephrase it:
start->fog->rEFInd->grub->ubuntu->KERNEL PANIC!
start->rEFInd (maybe)->grub->ubuntu->OK

**Comment by ZephyrBD** [comment]
> Is this a simple single disk setup, or are there multiple disks and or special partitions?
> You could try the grub exit option, but I'm unsure that will do the trick. You also don't have to leave a host booting to FOG every time after imaging, you can set things up to change the boot order after imaging. There are ways to make it change back on demand. 

I think restoring the original order works, but I've come across some weird computers before where the first boot option is PXE (even if it can't find a server), and they won't try the second boot option at all.

**Comment by darksidemilk** [comment]
To the point on virtual machines, there can be differences there but I don't think it would be the case here.

With the rEFInd exit mode it goes

start->fog/ipxe->rEFInd->grub->ubuntu->KERNEL PANIC!

With sanboot it should do this
start->fog/ipxe->firstDisk/grub->ubuntu->?

You could also try
start->fog/ipxe->fog-grub-exit-mode->grub->ubuntu->?

Since this works
start->grub->ubuntu->OK 
it's just a matter of finding the right way to exit the ipxe menu into the local grub.

You could also mess with ipxe.efi vs snponly.efi it's uncommon for that to make a difference at that point, but I have seen it happen.


I did also just see that we didn't add trying multiple disks to sanboot in 1.5.10.x but we did in 1.6.x (which is what I am using in production). 
I just pushed a change to the dev branch, you can update to it by going to where you downloaded fog from git (i.e. `/root/fogproject` ) on your server and running 

```
sudo -i
cd /root/fogproject
#update all branches
git fetch --all
#switch to dev-branch
git checkout dev-branch
git pull
cd /root/fogproject/bin
./installfog.sh
```

(see also https://docs.fogproject.org/en/latest/install-fog-server)

You could also manually edit the `bootmenu.class.php` file on your server. 
It should be at `/var/www/fog/lib/fog/bootmenu.class.php` and you can try changing line 130 from

```
$sanboot = 'sanboot --no-describe --drive 0x80';
```

to

```
$sanboot = 'console && sanboot --drive 0 --no-describe || sanboot --no-describe --drive 0x80 || sanboot --no-describe --drive 0x81 || sanboot --no-describe --drive 0x82';
```

Then try the sanboot exit mode again as it will likely find the partition/disk where the grub bootloader exists and boot to it correctly now.

**Comment by ZephyrBD** [comment]
Thanks. The method of modifying the file at the path /var/www/fog/lib/fog/bootmenu.class.php, specifically changing line 130 from 

```text
sanboot ='sanboot --no - describe --drive 0x80';`
```
to 

```text
sanboot = 'console && sanboot --drive 0 --no - describe || sanboot --no - describe --drive 0x80 || sanboot --no - describe --drive 0x81 || sanboot --no - describe --drive 0x82';
```

is effective. Now I can enter the system normally.

**Comment by darksidemilk** [comment]
Great to hear!

Just gonna try to link the commit
d54726c840beeb0e4a2e06a5cafe60877b8c53c9
